name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MinGW
      uses: msys2/setup-msys2-action@v2
      with:
        msystem: MINGW64

    - name: Build C++ application
      run: |
        g++ -o WindowManager.exe WindowManager.cpp -static -lgdi32 -luser32
    
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: WindowManager.exe
